CREATE SCHEMA IF NOT EXISTS fleetflow;
SET search_path TO fleetflow;
CREATE TABLE IF NOT EXISTS schema_migrations (
  version integer PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS departments (
  department_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_name varchar(80) NOT NULL UNIQUE CHECK (length(trim(department_name)) > 0)
);
CREATE TABLE IF NOT EXISTS employees (
  employee_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_code varchar(32) GENERATED ALWAYS AS
    ('EMP' || lpad(employee_id::text, greatest(4, length(employee_id::text)), '0')) STORED UNIQUE,
  department_id bigint NOT NULL REFERENCES departments ON DELETE RESTRICT,
  employee_name varchar(80) NOT NULL CHECK (length(trim(employee_name)) > 0),
  password varchar(128)
);
CREATE TABLE IF NOT EXISTS employee_phones (
  phone_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id bigint NOT NULL REFERENCES employees ON DELETE CASCADE,
  phone_number varchar(30) NOT NULL,
  UNIQUE (employee_id, phone_number)
);
CREATE TABLE IF NOT EXISTS vehicles (
  vehicle_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  license_plate varchar(20) NOT NULL UNIQUE,
  vehicle_model varchar(100) NOT NULL,
  vehicle_status varchar(20) NOT NULL DEFAULT 'available'
    CHECK (vehicle_status IN ('available', 'maintenance', 'retired'))
);
CREATE TABLE IF NOT EXISTS applications (
  application_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id bigint NOT NULL REFERENCES employees ON DELETE RESTRICT,
  purpose varchar(500) NOT NULL CHECK (length(trim(purpose)) > 0),
  requested_start_date timestamptz NOT NULL,
  requested_end_date timestamptz NOT NULL,
  approval_status varchar(20) NOT NULL DEFAULT 'pending'
    CHECK (approval_status IN ('pending','approved','rejected','cancelled')),
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (requested_end_date > requested_start_date)
);
CREATE TABLE IF NOT EXISTS dispatches (
  dispatch_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id bigint NOT NULL UNIQUE REFERENCES applications ON DELETE RESTRICT,
  vehicle_id bigint NOT NULL REFERENCES vehicles ON DELETE RESTRICT,
  actual_start_date timestamptz NOT NULL,
  actual_end_date timestamptz NOT NULL,
  returned_at timestamptz,
  CHECK (actual_end_date > actual_start_date),
  CHECK (returned_at IS NULL OR returned_at >= actual_start_date)
);
CREATE TABLE IF NOT EXISTS maintenance_records (
  vehicle_id bigint NOT NULL REFERENCES vehicles ON DELETE RESTRICT,
  maintenance_date date NOT NULL,
  maintenance_item varchar(250) NOT NULL,
  maintenance_cost numeric(12,2) NOT NULL CHECK (maintenance_cost >= 0),
  PRIMARY KEY (vehicle_id, maintenance_date)
);
CREATE TABLE IF NOT EXISTS refueling_records (
  vehicle_id bigint NOT NULL REFERENCES vehicles ON DELETE RESTRICT,
  refueling_date date NOT NULL,
  fuel_liters numeric(9,3) NOT NULL CHECK (fuel_liters > 0),
  fuel_cost numeric(12,2) NOT NULL CHECK (fuel_cost >= 0),
  PRIMARY KEY (vehicle_id, refueling_date)
);
CREATE INDEX IF NOT EXISTS ix_employees_department ON employees(department_id);
CREATE INDEX IF NOT EXISTS ix_applications_employee ON applications(employee_id);
CREATE INDEX IF NOT EXISTS ix_applications_status ON applications(approval_status);
CREATE INDEX IF NOT EXISTS ix_dispatches_vehicle_period ON dispatches(vehicle_id,actual_start_date,actual_end_date);
CREATE INDEX IF NOT EXISTS ix_refueling_vehicle ON refueling_records(vehicle_id);
INSERT INTO schema_migrations(version) VALUES (1) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS auth_sessions (
  session_hash varchar(64) PRIMARY KEY,
  employee_id bigint NOT NULL REFERENCES employees ON DELETE CASCADE,
  csrf_token varchar(64) NOT NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_sessions_employee ON auth_sessions(employee_id);
CREATE INDEX IF NOT EXISTS ix_sessions_expiry ON auth_sessions(expires_at);
CREATE TABLE IF NOT EXISTS auth_login_limits (
  bucket varchar(80) PRIMARY KEY,
  attempts integer NOT NULL DEFAULT 0 CHECK(attempts>=0),
  window_start timestamptz NOT NULL DEFAULT now()
);
