"""Exercise legacy-to-date migration in disposable schemas, including rollback."""
import uuid
import pytest
import psycopg
from psycopg import sql
from backend.db import connection, ROOT

@pytest.mark.parametrize('duplicate_table', [None, 'maintenance_records', 'refueling_records'])
def test_date_key_migration_preserves_or_rolls_back(duplicate_table):
    name='fleetflow_test_'+uuid.uuid4().hex[:12]
    migration=(ROOT/'backend/migrations/004_date_partial_keys.sql').read_text(encoding='utf-8')
    with connection() as c:
        c.execute(sql.SQL('CREATE SCHEMA {}').format(sql.Identifier(name)))
        c.execute(sql.SQL('SET search_path TO {}').format(sql.Identifier(name)))
        c.execute('''CREATE TABLE vehicles(vehicle_id bigint PRIMARY KEY);
            INSERT INTO vehicles VALUES(1),(2);
            CREATE TABLE schema_migrations(version integer PRIMARY KEY);
            CREATE TABLE maintenance_records(vehicle_id bigint REFERENCES vehicles,maintenance_seq integer,
                maintenance_date date NOT NULL,maintenance_item text,maintenance_cost numeric,PRIMARY KEY(vehicle_id,maintenance_seq));
            CREATE TABLE refueling_records(refueling_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                vehicle_id bigint REFERENCES vehicles,refueling_date date NOT NULL,fuel_liters numeric,fuel_cost numeric);
            INSERT INTO maintenance_records VALUES(1,1,'2026-10-01','Oil',100),(1,2,'2026-10-02','Tyres',200),(2,1,'2026-10-01','Oil',100);
            INSERT INTO refueling_records(vehicle_id,refueling_date,fuel_liters,fuel_cost) VALUES(1,'2026-10-01',10,350),(1,'2026-10-02',20,700),(2,'2026-10-01',10,350);''')
        if duplicate_table=='maintenance_records':
            c.execute("INSERT INTO maintenance_records VALUES(1,3,'2026-10-01','Duplicate',50)")
        elif duplicate_table=='refueling_records':
            c.execute("INSERT INTO refueling_records(vehicle_id,refueling_date,fuel_liters,fuel_cost) VALUES(1,'2026-10-01',5,175)")
    try:
        def apply():
            with connection() as c:
                c.execute(sql.SQL('SET search_path TO {}').format(sql.Identifier(name)))
                c.execute(migration)
        if duplicate_table:
            with pytest.raises(psycopg.errors.RaiseException,match='duplicate vehicle/date'):
                apply()
        else:
            apply();apply() # Safe to re-run, including fresh date-key tables.
        with connection() as c:
            c.execute(sql.SQL('SET search_path TO {}').format(sql.Identifier(name)))
            for table,date,legacy in [('maintenance_records','maintenance_date','maintenance_seq'),('refueling_records','refueling_date','refueling_id')]:
                assert c.execute(sql.SQL('SELECT count(*) n FROM {}').format(sql.Identifier(table))).fetchone()['n']==(4 if duplicate_table==table else 3)
                columns=[r['column_name'] for r in c.execute('SELECT column_name FROM information_schema.columns WHERE table_schema=%s AND table_name=%s',(name,table))]
                assert (legacy in columns)==bool(duplicate_table)
                key=c.execute("SELECT pg_get_constraintdef(oid) AS key FROM pg_constraint WHERE conrelid=%s::regclass AND contype='p'",(table,)).fetchone()['key']
                if not duplicate_table:
                    assert key==f'PRIMARY KEY (vehicle_id, {date})'
            assert c.execute('SELECT count(*) n FROM schema_migrations WHERE version=4').fetchone()['n']==(0 if duplicate_table else 1)
    finally:
        assert name.startswith('fleetflow_test_') and len(name)==27
        with connection() as c:
            c.execute(sql.SQL('DROP SCHEMA {} CASCADE').format(sql.Identifier(name)))
