ALTER TABLE employee_phones ADD COLUMN IF NOT EXISTS phone_id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE employee_phones DROP CONSTRAINT IF EXISTS employee_phones_pkey;
ALTER TABLE employee_phones ADD PRIMARY KEY (phone_id);
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid='employee_phones'::regclass AND conname='employee_phones_employee_id_phone_number_key'
  ) THEN
    ALTER TABLE employee_phones ADD CONSTRAINT employee_phones_employee_id_phone_number_key UNIQUE (employee_id,phone_number);
  END IF;
END $$;
INSERT INTO schema_migrations(version) VALUES (3) ON CONFLICT DO NOTHING;
